fix: trying to fix a sudden error with the 'platform-api' gem on heroku
Error was:

NoMethodError: undefined method `[]' for #<Enumerator:
/tmp/build_2162245362a290c18d53dbd462e22d15/config/initializers/heroku.rb:30:in
`<top (required)>'

See: https://travis-ci.org/basimilch/basimilch-app/builds/134073877